#!name=哔哩哔哩去广告

#!desc=哔哩哔哩去广告

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/biliad.png

#!homepage=https://whatshub.top

#!author=ddgksf2013



[MITM]

hostname= %APPEND% app.bilibili.com,api.live.bilibili.com,api.vc.bilibili.com, api.bilibili.com, manga.bilibili.com, grpc.biliapi.net,api.biliapi.net, -broadcast.chat.bilibili.com, -*cdn*.biliapi.net, -*tracker*.biliapi.net


[Script]


#～BiliBili_哔哩哔哩_推荐去广告@ddgksf2013

biliad6=type=http-response,pattern=^https?:\/\/app\.bilibili\.com\/x\/v2\/feed\/index,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js

#～BiliBili_哔哩哔哩_追番去广告@ddgksf2013

biliad7=type=http-response,pattern=^https?:\/\/api\.(bilibili|biliapi)\.(com|net)\/pgc\/page\/bangumi,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js

#～BiliBili_哔哩哔哩_直播去广告@bm7

biliad8=type=http-response,pattern=^https?:\/\/api\.live\.bilibili\.com\/xlive\/app-room\/v1\/index\/getInfoByRoom,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js

#～BiliBili_哔哩哔哩_动态去广告@bm7

biliad9=type=http-response,pattern=^https?:\/\/api\.vc\.bilibili\.com\/dynamic_svr\/v1\/dynamic_svr\/dynamic_(history|new)\?,requires-body=1,script-path=https://raw.githubusercontent.com/deezertidal/private/master/js-backup/Script/bilibili_json.js


[Map Local]
^https?:\/\/app\.bilibili\.com\/x\/resource\/top\/activity data="https://raw.githubusercontent.com/deezertidal/Surge_Module/master/files/reject-dict.json"
^https://app.bilibili.com/x/v2/splash/show data="https://raw.githubusercontent.com/deezertidal/Surge_Module/master/files/reject-dict.json"
^https://app.bilibili.com/x/v2/search/defaultwords data="https://raw.githubusercontent.com/deezertidal/Surge_Module/master/files/reject-dict.json"
^https?:\/\/api\.bilibili\.com\/x\/vip\/ads\/material\/report data="https://raw.githubusercontent.com/deezertidal/Surge_Module/master/files/reject-dict.json"
^https://api.bilibili.com/pgc/season/player/cards data="https://raw.githubusercontent.com/deezertidal/Surge_Module/master/files/reject-dict.json"
^https?:\/\/api\.vc\.bilibili\.com\/topic_svr\/v1\/topic_svr data="https://raw.githubusercontent.com/deezertidal/Surge_Module/master/files/reject-dict.json"
^https?:\/\/api\.bilibili\.com\/pgc\/season\/app\/related\/recommend\? data="https://raw.githubusercontent.com/deezertidal/Surge_Module/master/files/reject-dict.json"
^https?:\/\/manga\.bilibili\.com\/twirp\/comic\.v\d\.Comic\/(Flash|ListFlash) data="https://raw.githubusercontent.com/deezertidal/Surge_Module/master/files/reject-dict.json"
